AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Template rds_mysql.'
Parameters:
  Namespace:
    Description: Name of the Stack Namespace
    AllowedPattern: '[-a-zA-Z0-9]*'
    ConstraintDescription: ''
    MaxLength: '20'
    MinLength: '1'
    Type: String
  VpcId:
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    Type: AWS::EC2::VPC::Id
  SubnetIDs:
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
    Type: List<AWS::EC2::Subnet::Id>
  InstanceType:
    AllowedValues:
    - db.t1.micro
    - db.t2.micro
    - db.t2.small
    - db.t2.medium
    - db.t2.large
    - db.m1.small
    - db.m1.medium
    - db.m1.large
    - db.m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - db.m3.medium
    - db.m3.large
    - db.m3.xlarge
    - db.m3.2xlarge
    - db.m4.large
    - db.m4.xlarge
    - db.m4.2xlarge
    - db.m4.4xlarge
    - db.m4.10xlarge
    - db.r3.large
    - db.r3.xlarge
    - db.r3.2xlarge
    - db.r3.4xlarge
    - db.r3.8xlarge
    ConstraintDescription: must be a valid Database instance type.
    Default: db.t2.micro
    Description: The database instance type
    Type: String
  StorageType:
    Description: Specifies the storage type to be associated with the DB instance
    Default: gp2
    Type: String
    AllowedValues:
    - standard
    - gp2
    - io1
  DBAllocatedStorage:
    ConstraintDescription: must be between 5 and 1024Gb
    Default: 5
    Description: The size of the database (Gb)
    MinValue: 5
    MaxValue: 1024
    Type: Number
  DBName:
    Description: The first database name
    Type: String
    MaxLength: '64'
  DBUser:
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Default: admin
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    Description: The database admin account password
    NoEcho: true
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  EngineVersion:
    Description: The database version
    Type: String
    MinLength: '1'
    Default: 5.7
    AllowedValues:
    - 5.5
    - 5.6
    - 5.7
  MultiAZ:
    Type: String
    Default: false
    AllowedValues:
    - true
    - false
    ConstraintDescription: must be either true or false.
  PubliclyAccessible:
    Type: String
    Default: false
    AllowedValues:
    - true
    - false
  PreferredBackupWindow:
    Type: String
    Default: 05:00-06:00
  PreferredMaintenanceWindow:
    Type: String
    Default: sun:19:00-sun:20:00
  StorageEncrypted:
    Type: String
    Default: false
    AllowedValues:
    - true
    - false
  BackupRetentionPeriod:
    Type: Number
    Default: 7
    Description: The number of days during which automatic DB snapshots are retained.
    MinValue: 0
  InnodbLockWaitTimeout:
    Type: Number
    Default: 10
  InnodbMaxDirtyPagesPct:
    Type: Number
    Default: 90
  MaxHeapTableSize:
    Type: Number
    Default: 33554432
  TmpTableSize:
    Type: Number
    Default: 33554432
  ThreadCacheSize:
    Type: Number
    Default: 32
  LcTimeNames:
    Type: String
    Default: en_US
    AllowedValues:
    - de_DE
    - en_US
    - fr_FR
    - it_IT
    - ja_JP
    - pt_BR
    - zh_TW
  DBCharSet:
    Type: String
    Default: utf8
    AllowedValues:
    - ascii
    - latin1
    - sjis
    - utf8
    - cp932
  CollationServer:
    Type: String
    MinLength: '1'
    Default: utf8_general_ci
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Instance Configuration
      Parameters:
      - Namespace
      - VpcId
      - SubnetIDs
      - MultiAZ
      - PubliclyAccessible
      - InstanceType
      - DBAllocatedStorage
      - StorageType
      - DBName
      - DBUser
      - DBPassword
      - EngineVersion
      - StorageEncrypted
      - BackupRetentionPeriod
      - PreferredBackupWindow
      - PreferredMaintenanceWindow
    - Label:
        default: ParameterGroup Configuration
      Parameters:
      - InnodbLockWaitTimeout
      - InnodbMaxDirtyPagesPct
      - MaxHeapTableSize
      - TmpTableSize
      - ThreadCacheSize
      - LcTimeNames
      - DBCharSet
      - CollationServer
Mappings:
  MySQLParamGroupFamily:
    '5.5':
      Family: MySQL5.5
    '5.6':
      Family: MySQL5.6
    '5.7':
      Family: MySQL5.7
Resources:
  VPCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Security group for RDS DB Instance.
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/16
        FromPort: '3306'
        IpProtocol: tcp
        ToPort: '3306'
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - ' - '
          - - Ref: Namespace
            - 'VPC Security Group'
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance.
      SubnetIds: !Ref SubnetIDs
  DBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family:
        !FindInMap [MySQLParamGroupFamily, !Ref EngineVersion, Family]
      Description: Database Parameter Group.
      Parameters:
        character_set_client: !Ref DBCharSet
        character_set_connection: !Ref DBCharSet
        character_set_database: !Ref DBCharSet
        character_set_filesystem: !Ref DBCharSet
        character_set_results: !Ref DBCharSet
        character_set_server: !Ref DBCharSet
        collation_server: !Ref CollationServer
        general_log: 1
        innodb_buffer_pool_dump_at_shutdown: 1
        innodb_buffer_pool_load_at_startup: 1
        innodb_lock_wait_timeout: !Ref InnodbLockWaitTimeout
        innodb_max_dirty_pages_pct: !Ref InnodbMaxDirtyPagesPct
        lc_time_names: !Ref LcTimeNames
        log_output: FILE
        long_query_time: 1
        max_heap_table_size: !Ref MaxHeapTableSize
        query_cache_size: 0
        query_cache_type: 0
        skip-character-set-client-handshake: 0
        slow_query_log: 1
        thread_cache_size: !Ref ThreadCacheSize
        tmp_table_size: !Ref TmpTableSize
      Tags:
      - Key: Name
        Value: !Join ['.', [!Ref 'Namespace', !FindInMap [MySQLParamGroupFamily, !Ref 'EngineVersion', Family]]]
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AvailabilityZone: ap-northeast-1a
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceIdentifier:
        Fn::Join:
        - '-'
        - - Ref: Namespace
          - 'mysql'
      DBInstanceClass: !Ref InstanceType
      DBName: !Ref DBName
      DBParameterGroupName: !Ref DBParamGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: MySQL
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: !Ref MultiAZ
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      PubliclyAccessible: !Ref PubliclyAccessible
      StorageEncrypted: !Ref StorageEncrypted
      StorageType: !Ref StorageType
      VPCSecurityGroups:
        - Ref: VPCSecurityGroup
      Tags:
      - Key: Name
        Value: MySQL Master Database
      - Key: Application
        Value: !Ref AWS::StackId
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:mysql://
        - Fn::GetAtt:
          - DBInstance
          - Endpoint.Address
        - ':'
        - Fn::GetAtt:
          - DBInstance
          - Endpoint.Port
        - /
        - Ref: DBName
